- name: Check if file is connected to main.yml
  debug:
    msg: "Hello, this is Ubuntu!"

- name: Install apache2 httpd for Ubuntu (debian)
  apt:
    name: apache2
    state: latest
  
- name: Install unzip for Ubuntu (debian)
  apt:
    name: unzip
    state: latest

- name: Check if apache2 is running
  service:
    name: apache2
    state: started
    
- name: Download and unarchive into /var/www/html
  ansible.builtin.unarchive:
    src: https://www.free-css.com/assets/files/free-css-templates/download/page248/cube.zip
    dest: /var/www/html
    remote_src: yes